version: '3'

services: 
  php-fpm:
    build:
      context: ./php-fpm 
    volumes:
      - ../src:/var/www
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
    #command: --explicit_defaults_for_timestamp
    volumes:
      - ../src:/var/www
      - ./mysql/data:/var/lib/mysql      
      - ./logs:/var/log 
    environment:
      MYSQL_ROOT_PASSWORD : "root"
      MYSQL_DATABASE : "bot"
      MYSQL_USER : "botuser"
      MYSQL_PASSWORD : "botpass"
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
